export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";


///// COLLAB PAGE
// Room
export const SET_USER_NAME = "SET_USER_NAME"
export const SET_GUEST_ID = "SET_GUEST_ID"
export const SET_USER_SOCKET = "SET_USER_SOCKET";
export const SET_ROOM_CODE = "SET_ROOM_CODE";
export const SET_HOST_NAME = "SET_HOST_NAME";
export const UPDATE_CURRENT_GUESTS = "UPDATE_CURRENT_GUESTS";
export const UPDATE_CURRENT_GUEST_OBJECT = "UPDATE_CURRENT_GUEST_OBJECT"
export const OPEN_INVITE_GUESTS_WINDOW = "OPEN_INVITE_GUESTS_WINDOW"
export const CLOSE_INVITE_GUESTS_WINDOW = "CLOSE_INVITE_GUESTS_WINDOW"
export const SET_INVITATION_LINK = "SET_INVITATION_LINK"
export const OPEN_INVITE_GUESTS_ALERT = "OPEN_INVITE_GUESTS_ALERT"
export const CLOSE_INVITE_GUESTS_ALERT = "CLOSE_INVITE_GUESTS_ALERT"

// Document Info
export const SET_CURRENT_DOC = "SET_CURRENT_DOC";
export const SET_CANVAS_CONTAINER_REF = "SET_CANVAS_CONTAINER_REF";
export const SET_NUM_PAGES = "SET_NUM_PAGES";
export const SET_PAGE_DIMENSIONS = "SET_PAGE_DIMENSIONS";
export const SET_RENDERFABRICCANVAS_FUNC = "SET_RENDERFABRICCANVAS_FUNC";

// Tools
export const SET_CURRENT_ZOOM = "SET_CURRENT_ZOOM";
export const UPDATE_PAGES_ZOOMS = "UPDATE_PAGES_ZOOMS";
export const SET_PANEL_TOGGLE = "SET_PANEL_TOGGLE";
export const SET_TOOL_MODE = "SET_TOOL_MODE";
export const SET_PREV_TOOL_MODE = "SET_PREV_TOOL_MODE";
export const SET_IS_DOWN = "SET_IS_DOWN";
export const SET_CLIENT_X = "SET_CLIENT_X";
export const SET_CLIENT_Y = "SET_CLIENT_Y";
export const SET_SHAPE_OPACITY = "SET_SHAPE_OPACITY";
export const SET_SHAPE_BORDER_THICKNESS = "SET_SHAPE_BORDER_THICKNESS";
export const SET_SHAPE_BORDER_COLOR = "SET_SHAPE_BORDER_COLOR";
export const SET_SHAPE_FILL_COLOR = "SET_SHAPE_FILL_COLOR";
export const SET_SHAPE_FOCUS = "SET_SHAPE_FOCUS";
export const SET_SHAPE = "SET_SHAPE";
export const SET_DRAW_OPACITY = "SET_DRAW_OPACITY";
export const SET_DRAW_BRUSH_SIZE = "SET_DRAW_BRUSH_SIZE";
export const SET_DRAW_COLOR = "SET_DRAW_COLOR";
export const SET_TEXT_COLOR = 'SET_TEXT_COLOR';
export const SET_TEXT_OPACITY = 'SET_TEXT_OPACITY';
export const SET_TEXT_FONT_SIZE = 'SET_TEXT_FONT_SIZE';
export const ADD_HIGHLIGHT = 'ADD_HIGHLIGHT';
export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_PAGE_HIGHLIGHT = 'ADD_PAGE_HIGHLIGHT';
export const DELETE_HIGHLIGHT = 'DELETE_HIGHLIGHT';
export const SET_PANEL_MODE = 'SET_PANEL_MODE';


// Pilot Mode
// state
export const SET_PM_STATE = "SET_PM_STATE";

//  modal window
export const OPEN_PM_CONFIRM_WINDOW = "OPEN_PM_CONFIRM_WINDOW";
export const CLOSE_PM_CONFIRM_WINDOW = "CLOSE_PM_CONFIRM_WINDOW";
export const OPEN_PM_WAIT_WINDOW = "OPEN_PM_WAIT_WINDOW";
export const CLOSE_PM_WAIT_WINDOW = "CLOSE_PM_WAIT_WINDOW";
export const SET_PM_WAIT_WINDOW_TABLE_ROWS = "SET_PM_WAIT_WINDOW_TABLE_ROWS";

export const SET_PM_REQUESTER_SOCKET_ID = "SET_PM_REQUESTER_SOCKET_ID";
