# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy CI

on:
  push:
    branches: [ production ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /var/www/cosign.pro/CollaborativeForms
            git fetch origin production
            git reset --hard origin/production
            sudo rsync -av --delete /var/www/cosign.pro/CollaborativeForms/node-server/ /var/www/cosign.pro/backend
            cd /var/www/cosign.pro/backend 
            sudo touch /var/www/cosign.pro/backend/.env
            echo BUG_REPORT_EMAIL_ADDRESS=${{ secrets.BUG_REPORT_EMAIL_ADDRESS }} | sudo tee -a /var/www/cosign.pro/backend/.env
            echo CONTACT_EMAIL_ADDRESS=${{ secrets.CONTACT_EMAIL_ADDRESS }} | sudo tee -a /var/www/cosign.pro/backend/.env
            echo "ENCRYPT_KEY=${{ secrets.ENCRYPT_KEY }}" | sudo tee -a /var/www/cosign.pro/backend/.env
            echo JWT_PRIVATE_KEY=${{ secrets.JWT_PRIVATE_KEY }} | sudo tee -a /var/www/cosign.pro/backend/.env
            echo MAILER_LOGIN=${{ secrets.MAILER_LOGIN }} | sudo tee -a /var/www/cosign.pro/backend/.env
            echo "MAILER_PASSWORD=${{ secrets.MAILER_PASSWORD }}" | sudo tee -a /var/www/cosign.pro/backend/.env
            echo NODE_ENV=${{ secrets.NODE_ENV }} | sudo tee -a /var/www/cosign.pro/backend/.env
            echo S3_BUCKET_ACCESS_KEY=${{ secrets.S3_BUCKET_ACCESS_KEY }} | sudo tee -a /var/www/cosign.pro/backend/.env
            echo S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }} | sudo tee -a /var/www/cosign.pro/backend/.env
            echo S3_BUCKET_REGION=${{ secrets.S3_BUCKET_REGION }} | sudo tee -a /var/www/cosign.pro/backend/.env
            echo S3_BUCKET_SECRET_ACCESS_KEY=${{ secrets.S3_BUCKET_SECRET_ACCESS_KEY }} | sudo tee -a /var/www/cosign.pro/backend/.env
            echo STRIPE_WEBHOOK_SECRET=${{ secrets.STRIPE_WEBHOOK_SECRET }} | sudo tee -a /var/www/cosign.pro/backend/.env
            echo STRIPE_API_KEY=${{ secrets.STRIPE_API_KEY }} | sudo tee -a /var/www/cosign.pro/backend/.env
            echo STRIPE_PUBLIC_API_KEY=${{ secrets.STRIPE_PUBLIC_API_KEY }} | sudo tee -a /var/www/cosign.pro/backend/.env
            echo GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} | sudo tee -a /var/www/cosign.pro/backend/.env
            echo GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} | sudo tee -a /var/www/cosign.pro/backend/.env
            echo FACEBOOK_APP_ID=${{ secrets.FACEBOOK_APP_ID }} | sudo tee -a /var/www/cosign.pro/backend/.env
            echo FACEBOOK_APP_SECRET=${{ secrets.FACEBOOK_APP_SECRET }} | sudo tee -a /var/www/cosign.pro/backend/.env
            echo LINKEDIN_API_KEY=${{ secrets.LINKEDIN_API_KEY }} | sudo tee -a /var/www/cosign.pro/backend/.env
            echo LINKEDIN_SECRET_KEY=${{ secrets.LINKEDIN_SECRET_KEY }} | sudo tee -a /var/www/cosign.pro/backend/.env
            echo EXPRESS_SESSION_SECRET=${{ secrets.EXPRESS_SESSION_SECRET }} | sudo tee -a /var/www/cosign.pro/backend/.env
            echo BACKEND_ADDRESS=${{ secrets.BACKEND_ADDRESS }} | sudo tee -a /var/www/cosign.pro/backend/.env
            echo FRONTEND_ADDRESS=${{ secrets.FRONTEND_ADDRESS }} | sudo tee -a /var/www/cosign.pro/backend/.env
            sudo npm install --unsafe-perm
            cd /var/www/cosign.pro/CollaborativeForms/client
            sudo npm install --unsafe-perm
            sudo touch /var/www/cosign.pro/CollaborativeForms/client/.env.production
            echo REACT_APP_BACKEND_ADDRESS=https://cosign.pro | sudo tee -a /var/www/cosign.pro/CollaborativeForms/client/.env.production
            echo REACT_APP_FRONTEND_ADDRESS=https://cosign.pro | sudo tee -a /var/www/cosign.pro/CollaborativeForms/client/.env.production
            echo REACT_APP_STRIPE_PUBLIC_API_KEY=${{ secrets.STRIPE_PUBLIC_API_KEY }} | sudo tee -a /var/www/cosign.pro/CollaborativeForms/client/.env.production
            sudo npm run build --prefix /var/www/cosign.pro/CollaborativeForms/client/
            sudo rsync -av --delete /var/www/cosign.pro/CollaborativeForms/client/build/ /var/www/cosign.pro/html
            pm2 reload server
            sudo systemctl reload nginx