# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy CI

on:
  push:
    branches: [ production ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /var/www/cosign.pro/
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S git clone -b production https://github.com/harrisonwjs/CollaborativeForms.git
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S rsync -av --delete /var/www/cosign.pro/CollaborativeForms/node-server /var/www/cosign.pro/backend
            cd /var/www/cosign.pro/backend
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S npm install # install dependencies 
            cd ..
            cd /var/www/cosign.pro/CollaborativeForms/client
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S npm install
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S npm run build
            cd ..
            cd ..
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S rsync -av --delete /var/www/cosign.pro/CollaborativeForms/client /var/www/cosign.pro/html
            pm2 reload server
